/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#a3132b",
        "on-tertiary": "#470481",
        "surface-card": "#181720",
        "surface-container": "#1f1f24",
        "error-container": "#93000a",
        "primary": "#ffb3b3",
        "background": "#131317",
        "surface": "#131317",
        "tertiary-fixed": "#efdbff",
        "on-background": "#e4e1e7",
        "on-tertiary-fixed": "#2b0053",
        "outline": "#a98989",
        "primary-fixed": "#ffdad9",
        "on-error-container": "#ffdad6",
        "void-black": "#050507",
        "on-secondary-fixed": "#341100",
        "on-primary-container": "#ffb2b2",
        "on-primary": "#680015",
        "on-surface": "#e4e1e7",
        "spectral-cyan": "#00F0FF",
        "tertiary-container": "#6a36a5",
        "surface-tint": "#ffb3b3",
        "tertiary": "#dbb8ff",
        "inverse-surface": "#e4e1e7",
        "on-primary-fixed-variant": "#920021",
        "on-error": "#690005",
        "surface-container-low": "#1b1b1f",
        "on-primary-fixed": "#400009",
        "error": "#ffb4ab",
        "bone-ivory": "#E8DDC8",
        "on-secondary": "#552100",
        "surface-container-high": "#2a292e",
        "inverse-on-surface": "#303035",
        "surface-variant": "#353439",
        "on-surface-variant": "#e2bebd",
        "surface-dark": "#121218",
        "on-tertiary-container": "#dab7ff",
        "on-tertiary-fixed-variant": "#5e2998",
        "crimson-glow": "#FF1E44",
        "secondary-fixed": "#ffdbcb",
        "outline-variant": "#5a4040",
        "on-secondary-fixed-variant": "#783100",
        "secondary-fixed-dim": "#ffb691",
        "surface-container-lowest": "#0e0e12",
        "inverse-primary": "#b52336",
        "surface-bright": "#39393d",
        "tertiary-fixed-dim": "#dbb8ff",
        "secondary": "#ffb691",
        "on-secondary-container": "#4a1c00",
        "border-subtle": "#2B283A",
        "surface-dim": "#131317",
        "primary-fixed-dim": "#ffb3b3",
        "secondary-container": "#e96c1b",
        "surface-container-highest": "#353439",
        "surface-hover": "#22202E"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "margin": "2.5rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "label-sm": ["Chivo", "sans-serif"],
        "display-lg": ["Bebas Neue", "cursive"],
        "body-sm": ["Chivo", "sans-serif"],
        "headline-md": ["Bebas Neue", "cursive"],
        "title-md": ["Chivo", "sans-serif"],
        "body-lg": ["Chivo", "sans-serif"],
        "title-lg": ["Chivo", "sans-serif"],
        "display-lg-mobile": ["Bebas Neue", "cursive"],
        "label-md": ["Chivo", "sans-serif"],
        "display-xl-mobile": ["Bebas Neue", "cursive"],
        "body-md": ["Chivo", "sans-serif"],
        "label-lg": ["Chivo", "sans-serif"],
        "headline-lg": ["Bebas Neue", "cursive"],
        "display-xl": ["Bebas Neue", "cursive"]
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg": ["3.5rem", { lineHeight: "3.75rem", letterSpacing: "0.04em", fontWeight: "400" }],
        "display-lg-mobile": ["2.5rem", { lineHeight: "2.75rem", letterSpacing: "0.03em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-md": ["1.75rem", { lineHeight: "2rem", letterSpacing: "0.03em", fontWeight: "400" }],
        "title-md": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "title-lg": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "0.01em", fontWeight: "700" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-xl-mobile": ["3.25rem", { lineHeight: "3.25rem", letterSpacing: "0.04em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.5rem", letterSpacing: "0.04em", fontWeight: "400" }],
        "display-xl": ["5rem", { lineHeight: "5rem", letterSpacing: "0.05em", fontWeight: "400" }]
      }
    }
  }
};
